script: bundle exec rspec
language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.0
  - 2.5.0

env:
  - RAILS_VERSION=3-2-stable
  - RAILS_VERSION=4-0-stable
  - RAILS_VERSION=4-1-stable
  - RAILS_VERSION=4-2-stable
  - RAILS_VERSION=5-0-stable
  - RAILS_VERSION=5-1-stable
  - RAILS_VERSION=5-2-stable
  - RAILS_VERSION=master

matrix:
  allow_failures:
    - env: RAILS_VERSION=master

